[package]
name = "backend"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.4"
rand = "0.9.1"
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1.45", features = ["full"] }
tower-http = { version = "0.5.2", features = ["cors"] }



